var AC = new (window.AudioContext || window.webkitAudioContext)();

export function sfx(t) {
  try {
    var n = AC.currentTime;
    if (t==='click') { var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.frequency.setValueAtTime(880,n);o.frequency.exponentialRampToValueAtTime(440,n+.08);g.gain.setValueAtTime(.1,n);g.gain.exponentialRampToValueAtTime(.001,n+.1);o.start(n);o.stop(n+.1); }
    else if (t==='select') { var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.setValueAtTime(660,n);o.frequency.exponentialRampToValueAtTime(880,n+.12);g.gain.setValueAtTime(.13,n);g.gain.exponentialRampToValueAtTime(.001,n+.15);o.start(n);o.stop(n+.15); }
    else if (t==='confirm') { [523,659,784].forEach(function(f,i){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.1,n+i*.1);g.gain.exponentialRampToValueAtTime(.001,n+i*.1+.2);o.start(n+i*.1);o.stop(n+i*.1+.22);}); }
    else if (t==='deal') { for(var i=0;i<5;i++){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='triangle';o.frequency.value=300+i*80;g.gain.setValueAtTime(.07,n+i*.06);g.gain.exponentialRampToValueAtTime(.001,n+i*.06+.1);o.start(n+i*.06);o.stop(n+i*.06+.12);} }
    else if (t==='flip') { var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='triangle';o.frequency.setValueAtTime(200,n);o.frequency.exponentialRampToValueAtTime(800,n+.3);g.gain.setValueAtTime(.13,n);g.gain.exponentialRampToValueAtTime(.001,n+.35);o.start(n);o.stop(n+.35); }
    else if (t==='night') { [220,196,174,165].forEach(function(f,i){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.09,n+i*.18);g.gain.exponentialRampToValueAtTime(.001,n+i*.18+.35);o.start(n+i*.18);o.stop(n+i*.18+.4);}); }
    else if (t==='wolf') { var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sawtooth';o.frequency.setValueAtTime(120,n);o.frequency.exponentialRampToValueAtTime(60,n+.6);g.gain.setValueAtTime(.14,n);g.gain.exponentialRampToValueAtTime(.001,n+.65);o.start(n);o.stop(n+.65); }
    else if (t==='protect') { [523,659,784,1047].forEach(function(f,i){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.08,n+i*.07);g.gain.exponentialRampToValueAtTime(.001,n+i*.07+.16);o.start(n+i*.07);o.stop(n+i*.07+.18);}); }
    else if (t==='vote') { var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='square';o.frequency.setValueAtTime(440,n);g.gain.setValueAtTime(.07,n);g.gain.exponentialRampToValueAtTime(.001,n+.3);o.start(n);o.stop(n+.3); }
    else if (t==='hang') { var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sawtooth';o.frequency.setValueAtTime(300,n);o.frequency.exponentialRampToValueAtTime(80,n+.8);g.gain.setValueAtTime(.16,n);g.gain.exponentialRampToValueAtTime(.001,n+.85);o.start(n);o.stop(n+.85); }
    else if (t==='win') { [523,659,784,1047,1319].forEach(function(f,i){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.1,n+i*.12);g.gain.exponentialRampToValueAtTime(.001,n+i*.12+.28);o.start(n+i*.12);o.stop(n+i*.12+.32);}); }
    else if (t==='dead') { [220,196,185,165].forEach(function(f,i){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.09,n+i*.15);g.gain.exponentialRampToValueAtTime(.001,n+i*.15+.28);o.start(n+i*.15);o.stop(n+i*.15+.32);}); }
    else if (t==='alarm') { for(var i=0;i<6;i++){var o=AC.createOscillator(),g=AC.createGain();o.connect(g);g.connect(AC.destination);o.type='square';o.frequency.value=i%2===0?880:660;g.gain.setValueAtTime(.18,n+i*.18);g.gain.exponentialRampToValueAtTime(.001,n+i*.18+.15);o.start(n+i*.18);o.stop(n+i*.18+.18);} }
  } catch(e) {}
}
