export function freshNc(prev) {
  prev = prev || {};
  return {
    wolfVictim: -1,
    wolfVictim2: -1,
    whitewolfVictim: -1,
    guardProtect: -1,
    guardLastNight: (typeof prev.guardLastNight === 'number') ? prev.guardLastNight : -1,
    witchSave: false,
    witchPoison: -1,
    witchSaveUsed: prev.witchSaveUsed || false,
    witchPoisonUsed: prev.witchPoisonUsed || false,
    priestUsed: prev.priestUsed || false,
    seerCheck: -1,
    cupidPair: [],
    loverPair: prev.loverPair || [],
    gangleaderCheck: -1,
    detectiveCheck: [],
    matchmakerUsed: prev.matchmakerUsed || false,
    matchmakerPair: prev.matchmakerPair || [],
    matchmakerNightPair: [],
    wildchildNightPick: -1,
    sorcererCheck: -1,
    foxCheck: [],
    whiteWitchUsed: prev.whiteWitchUsed || false,
    whiteWitchRevive: -1,
    seducedIdx: -1,
    wolfGuardProtect: -1,
    wolfSpyCheck: -1,
    demonWolfRevive: -1,
    demonWolfUsed: prev.demonWolfUsed || false,
    piCheck: -1,
    exorcistBlock: -1,
    exorcistUsed: prev.exorcistUsed || false,
    oracleCheck: -1
  };
}

export var st = {
  n: 10,
  roles: {},
  pinnedRoles: {},
  players: [],
  assigned: [],
  dealIdx: 0,
  cardFlipped: false,
  nightStep: 0,
  nightOrder: [],
  nc: freshNc(),
  voteMap: {},
  voteTopIdx: -1,
  timerSec: 180,
  timerTotal: 180,
  timerRunning: false,
  timerIv: null,
  prevScreen: 's-day',
  round: 1,
  gameLog: [],
  currentLogRound: null,
  hunterQueue: [],
  sheriffIdx: -1,
  sheriffPassQueue: [],
  gameOver: false,
  wolfDoubleKill: false,
  wildchildRoleModel: -1,
  foxAbilityLost: false
};
